data:
  images_df_file: /home/xiangqi/xiangqi/agenticRag/src/data/images.parquet
  images_embedding_df_file: /home/xiangqi/xiangqi/agenticRag/src/data/agentic_images_embeddings.parquet
  texts_df_file: /home/xiangqi/xiangqi/agenticRag/src/data/texts.parquet
  texts_embedding_df_file: /home/xiangqi/xiangqi/agenticRag/src/data/agentic_texts_embeddings.parquet
  agentic_data_root: /home/xiangqi/xiangqi/agenticRag/Database
  


app:
  dev_mode: False
  reset_vdb_on_startup: True

weaviate:
  host: localhost
  http_port: 8080
  grpc_port: 50051

mlflow:
  host: localhost
  port: 8081

agentic:
  ml_url: http://localhost:8001 